# Generic ESP32
substitutions:
  can_tx_pin: GPIO17
  can_rx_pin: GPIO16
  board: esp32dev
  variant: ESP32
  flash_size: 4MB
# Note: after changing the GPIO from 4-5 to 16-17 for rx-tx canbus, the issue about optionbox and comfoconnect hanging on vmc startup seems fixed
